#!/bin/bash

if [ "$#" -eq 1 ]; then
 echo "Script config path: $1" >&2
 source $1
 iotlab-auth -u ${USER} -p ${PASSWORD} || exit 1


# Redirect all nodes serial output to a file
readonly OUTFILE="${HOME}/.iot-lab/${EXP_ID}/aggregator_log"

echo "Launch serial_aggregator with exp_id: ${EXP_ID}" >&2
serial_aggregator -i ${EXP_ID} 2> /dev/null 1> ${OUTFILE}
